include = ["**/*.toml"]
exclude = ["target/**"]

[formatting]
reorder_keys = false
column_width = 120

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "dev-dependencies", "build-dependencies", "features", "workspace"]

[rule.formatting]
reorder_keys = true
array_auto_collapse = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["package", "workspace.package"]

[rule.formatting]
reorder_keys = false
array_auto_collapse = false
