[package]
name = "faucet-controller"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }
